server:
  port: 8085
spring:
  application:
    name: dbService
  datasource:
    url: jdbc:mysql://47.98.232.233:3306/student?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1284974404
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true